### ISSUE TITLE
Add examples, please

### ISSUE THREAD

**Issue by yuriMalakhov** [DaftMonk/generator-ng-component#37]
First time using your generator. Can't understand hot to generate anything. Please, improve your README.md and add some examples on how to generate module, controller, etc. Also, I would really appreciate if you explain how to configure yo-rc.json and what should I fill inside it's properties. Many thanks in advance.

**Comment by Awk34** [comment]
This generator is mainly used in [angular-fullstack/generator-angular-fullstack](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/docs/index.md), and we have the subgenerators documented there ([docs/index.md](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/docs/index.md)).

As for the `.yo-rc.json`, you can read about it [here](http://yeoman.io/authoring/storage.html), and take a look at an example [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/src/test/fixtures/.yo-rc.json).
