### ISSUE TITLE
route template: ControllerAs should be a string value and cannot be 'similar' to component name

### ISSUE THREAD

**Issue by carpaij** [DaftMonk/generator-ng-component#45]
When scaffolding out a new `route` it now uses the `controller as` approach, but it seems to be wrongly implemented in the template:
1. first of all the `controllerAs:` value should be a string and by convention should be camel case.
2. secondly it seems that the `controllerAs:` name has to be different from the component name itself (`cameledName`) and just the first letter being a capital doesn't seem to do the trick. Hence I propose to append `Ctrl` to the `controllerAs` name.

OLD
```javascript
angular.module('<%= scriptAppName %>')
  .component('<%= cameledName %>', {
    templateUrl: '<%= htmlUrl %>',
    controller: <%= classedName %>Component,
    controllerAs: <%= classedName %>
  });
```

NEW
```javascript
angular.module('<%= scriptAppName %>')
  .component('<%= cameledName %>', {
    templateUrl: '<%= htmlUrl %>',
    controller: <%= classedName %>Component,
    controllerAs: '<%= cameledName %>Ctrl'
  });
```

For your convenience I've created a pull request for you to review. Please let me know if I've missed something.

**Comment by Awk34** [comment]
merged

**Comment by carpaij** [comment]
Thnx @Awk34
