### ISSUE TITLE
Filter generator broken with default module name

### ISSUE THREAD

**Issue by carpaij** [DaftMonk/generator-ng-component#48]
Regarding [this](https://github.com/angular-fullstack/generator-angular-fullstack/issues/2055) issue I reported yesterday on generator-angular-fullstack, I believe the problem is with the generator-ng-component generator.

More specifically if you look at the `index.js` in `/src/generators/filter` you will see that the first element in `prompts` contains the `default` as a concatenation of the `scriptAppName` and the provided filter `name`. Removing this `.${this.name}` should do the trick.
```javascript
    var prompts = [{
      name: 'moduleName',
      message: 'What module name would you like to use?',
      default: `${this.scriptAppName}.${this.name}`,
      when: () => this.config.get('modulePrompt')
    },
```

However, I'm afraid I'm missing something as all the generators have this approach and it has been like this for months, although in a slightly different coding:
```javascript
      default: self.scriptAppName + '.' + self.name,
```

Please let me know if my suggestion is the correct one, and I will fix it in all the generator files and commit this for you to review.

**Comment by Awk34** [comment]
@carpaij in regards to generator-angular-fullstack@3.0.0, yes, having `default: self.scriptAppName` would be best. If you want to make a PR changing all the subgenerators here to that, against the *0.x.x* branch, I would probably merge it.

**Comment by carpaij** [comment]
@Awk34 Adding the changes on a fork of master and from there a PR to _0.x.x_?

**Comment by Awk34** [comment]
@carpaij a fork of *0.x.x*, and then a PR back onto *0.x.x*. Master currently contains changes for 1.0.0.

**Comment by carpaij** [comment]
@Awk34 will do!

**Comment by carpaij** [comment]
PR has been made #49 
Please close when you've merged the PR.

**Comment by Awk34** [comment]
@carpaij Protip: if you add `closes #xxx`, where `xxx` is the issue number, GitHub will automatically close the issue when the commit is merged onto *master*
